// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbrfdondzrqztqlfdmhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticmZkb25kenJxenRxbGZkbWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDMzODksImV4cCI6MjA3NDMxOTM4OX0.3GHGH4W5AzyiYfz3vPV7UJwZPn8ZRdD7g8evwjueY5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});